### ISSUE TITLE
Request for update of squamate database

### ISSUE THREAD

**Issue by bansal-udita** [ptitle/rangeBuilder#3]
Dear Dr. Title, 

Thank you so much for the wonderful package. I wanted to use the synonymMatch function to compare names across reptile datasets I am using that range from the year 2010 to 2019. The function details mention that the database will be updated regularly, but when I check dates, it shows me Oct 2016 reptile database is being used. Is that correct? In that case, would it be possible to update it to December 2019 version? It will be extremely helpful.

Thank you 
Sincerely, 
Udita Bansal

**Comment by ptitle** [comment]
I apologize, but this functionality has been removed. I hope to resurrect these tools in a separate tool sometime soon.
