### ISSUE TITLE
Issue with getDynamicAlphaHull

### ISSUE THREAD

**Issue by aberenicega** [ptitle/rangeBuilder#6]
Hi!
Thank you so much for this amazing package.

I was having problems with getDynamicAlphaHull function. My occurrences did not accomplish any condition to build an alpha hull, so the function should give a convex hull as a species' range. But, instead of that, I got a sf object with the same number of polygons as occurrences. As a solution, I reinstalled the package using the pre-release version from GitHub instead of the Cran version. I guess in this GitHub version, this function has already been fixed.
In addition, I guess you committed a typo in the path code
there is 
"remotes::install_github("ptitle/rangeBuilder/rangeBuilder")"
and the correct path is
"remotes::install_github("ptitle/rangeBuilder")"

Regards

**Comment by ptitle** [comment]
Hi,
The github version now more closely aligns with the CRAN version. If you are still having an issue, please provide code to reproduce the issue, and I will see what I can do.
