### ISSUE TITLE
Issues with getDynamicAlphaHull

### ISSUE THREAD

**Issue by kevinlopezreyes** [ptitle/rangeBuilder#7]
Good afternoon,

I'm experiencing two specific errors while using the "getDynamicAlphaHull" function.

First, when I set a buffer of 0, it creates empty polygons. I have to set a minimum value, for example, 1 km, for it to work properly.

The second error is related to modeling species that are distributed on islands or include islands within their distribution, and I try to clip them using the "terrestrial" argument. I suspect this second problem arises because the function includes the "medium" resolution of rnaturalearth, and not all islands are included in that resolution, resulting in empty polygons or errors in the function if I don't apply buffers.

I would like to know if there could be a way to select the resolution of the clipping (small, medium, and large). I have already tried modifying the original function without success.

Thank you in advance,

Kevin.

**Comment by ptitle** [comment]
Hi Kevin, 

Thank you for reporting these issues. I'll look into the zero buffer issue. Regarding the other one, I would recommend setting `clipToCoast = 'no'`, and then clipping your polygons with whichever vector file makes the most sense for you.

More soon.

**Comment by kevinlopezreyes** [comment]
Thank you Dr. Title,

I am going to implement that strategy.

Best regards, 

-Kevin.

**Comment by ptitle** [comment]
Kevin, I'm not able to reproduce your issue with zero buffers. Can you provide a reproducible example for me?
thanks!
