### ISSUE TITLE
getDynamicAlphaHull creating hundreds of tiny hulls

### ISSUE THREAD

**Issue by ecoblam** [ptitle/rangeBuilder#8]
I'm having an issue with getDynamicAlphaHull creating 100s or possibly 1000s of tiny hulls, basically scattered pixels, instead of joining a hull around the points. This only happens for some species and persists regardless of alterations in settings such as partCount or initialAlpha. Is this a known issue or likely to be the input data or user error?

**Comment by ptitle** [comment]
Hi,

This is not a known issue. It could potentially have to do with the input data, or may be related to the recent switch from sp to sf. If you don't mind emailing me data and a script that reproduces the issue, I'd be happy to take a look. My email is pascal.title[at]stonybrook.edu.

**Comment by ptitle** [comment]
Ok I fixed two bugs that were contributing to this. Can you please install from github and try it out? `remotes::install_github('ptitle/rangeBuilder')`. Let me know if it works better!

**Comment by ecoblam** [comment]
Hi Pascal,

I haven’t run the entire species list yet, but I ran it for the kultarr (a species that was failing) and it worked perfectly.

Thanks so much for fixing the issue in a prompt manner! Very much appreciated.

Regards,
William

**Comment by ptitle** [comment]
Excellent! If anything else comes up, be sure to report it!
