### ISSUE TITLE
getDynamicAlphaHull: Error in FUN(X[[i]], ...) : polygons require at least 4 points

### ISSUE THREAD

**Issue by zsherpa** [ptitle/rangeBuilder#9]
Thank you for this very useful package!

I'm having issues with getDynamicAlphaHull() for some species only (28 out of 1440 species). When running these specific species, I get the following error:

```r
> getDynamicAlphaHull(df, coordHeaders=c('lon','lat'), clipToCoast = 'terrestrial', partCount = 10, fraction = 0.95) 

Error in FUN(X[[i]], ...) : polygons require at least 4 points
``` 

I have checked the occurrence data and installed the package from Github. I'm thinking the error might be related to st_cast() in ah2sf() when the function converts LINESTRING to POLYGON objects. Is this a known issue ? Would it be possible to send a reproducible code for this error via e-mail ?

Thank you in advance,
Zoé

**Comment by ptitle** [comment]
Hi Zoé,
Sure, send me some reproducible code to pascal.title[at]stonybrook.edu and I can take a look.
This is not currently a known issue.

-Pascal
